language: node_js
node_js:
  - 11
cache:
  directories:
    - ~/.npm
    - ~/.cache
stages:
  - lint
  - test-unit
  - test-e2e
jobs:
  include:
    - stage: lint
      script:
        yarn run lint
    - stage: test-unit
      script:
        yarn run test:unit
    - stage: test-e2e
      script:
        yarn run test:e2e --headless
