language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
stages:
  - lint
  - test_unit
  - test_e2e
jobs:
  include:
    - stage: lint
      script:
        yarn run lint
    - stage: test_unit
      script:
        yarn run test:unit
    - stage: test_e2e
      script:
        yarn run test:e2e --headless
